service: gadgetzanGazette

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  profile: tcias

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: gadgetzan-gazette
          method: post
