service: blizzard-news-flash
frameworkVersion: "=1.14.0"
provider:
  name: aws
  runtime: nodejs6.10
  profile: tcias
  memorySize: 512 # Overwrite the default memory size. Default is 1024

functions:
  hello:
    handler: handler.hello
    events:
       - alexaSkill

package:
  exclude:
    - node_modules/**
